require 'nokogiri'

module Jekyll
  class NativeCodeEnhancer
    def self.process(content)
      # Post-render hooks receive the complete page HTML. Parsing it as a
      # fragment drops the doctype, html/head tags, and attributes such as
      # <html lang="...">.
      doc = if defined?(Nokogiri::HTML5::Document)
              Nokogiri::HTML5::Document.parse(content)
            else
              Nokogiri::HTML::Document.parse(content)
            end
      if doc.at_css('meta[charset]')
        doc.css('meta[http-equiv="Content-Type"]').each(&:remove)
      end
      
      # Find all code blocks generated by Rouge that have 'fold' or 'title' attributes
      # Kramdown adds these attributes to the outer div
      doc.css('div.highlighter-rouge').each do |block|
        fold = block['fold']
        title = block['title']
        type = block['type'] # e.g. success, info, warning, error, example, exploit
        
        # Only process if we have fold or title or type attributes
        next unless fold || title || type
        
        # Determine wrapper type
        if fold
          wrapper = Nokogiri::XML::Node.new('details', doc)
          wrapper['class'] = 'code_block'
          if type
            wrapper['class'] += " #{type}"
          end
          
          if fold == 'open'
            wrapper['open'] = 'open'
          end
          
          # Add summary for details
          summary = Nokogiri::XML::Node.new('summary', doc)
          if title
            summary['data-title'] = title
          end
          wrapper.add_child(summary)
        else
          wrapper = Nokogiri::XML::Node.new('div', doc)
          wrapper['class'] = 'code_block'
          if type
            wrapper['class'] += " #{type}"
          end
          
          if title
            wrapper['data-title'] = title
          end
        end
        
        # Clean up attributes from the original block to avoid duplication/conflicts
        block.remove_attribute('fold')
        block.remove_attribute('title')
        block.remove_attribute('type')
        
        # Replace block with wrapper containing block
        block.replace(wrapper)
        wrapper.add_child(block)
      end
      
      doc.to_html
    end
  end
end

Jekyll::Hooks.register [:documents, :pages], :post_render do |doc|
  # Only process HTML output
  if doc.output_ext == '.html'
    doc.output = Jekyll::NativeCodeEnhancer.process(doc.output)
  end
end
